# dump the object directory from an EtherCAT ESI file to a C++ header file

import re

boilerplate = '''#pragma once

// generated by EsiObjDirToCPPHeader

#include <cstdint>

namespace CANopen {

enum class Type
{
    BOOL,
    SINT,
    INT,
    DINT,
    LINT,
    USINT,
    BYTE,
    UINT,
    WORD,
    UDINT,
    DWORD,
    ULINT,
    LWORD,
    REAL,
    LREAL,
    STRING, // length in comment
    ENUM, // ST type in comment
    ARRAY // range and type in comment
};

struct ObjectAddress
{
   std::uint16_t index;
   std::uint8_t subindex;
   Type type;
};

'''

footer = '''
} // namespace CANopen
'''

indent = ''
namespace = ''

def is_invalid_c_symbol(name):
    if not name:
        return True
    first_char = name[0]
    return not first_char.isalpha() and first_char != '_'

def object_name_to_cpp_symbol(name):
    if '/' in name:
        section, subsection = name.split('/')
    else:
        section = ''
        subsection = name
    # fixup names like 1st and 2nd by prefixing with X_
    if is_invalid_c_symbol(section):
        section = 'X_' + section
    if is_invalid_c_symbol(subsection):
        subsection = 'X_' + subsection
    return section.replace(' ', '_'), subsection.replace(' ', '_')

def object_index_to_cpp_hex(index):
    return index.replace('#', '0')

def object_subindex_to_cpp_number(subindex):
    if '' == subindex:
        return 0
    else:
        return int(subindex)

def translateType(raw_type):
    # if type is a string or enum, provide a proxy
    if '(' in raw_type:
        # leave the contents of the parens as a comment
        return re.sub(r'\(([0-9]+)\)', r'/* \1 */', raw_type)
    if raw_type.startswith('DT'):
        return 'ENUM /* ' + raw_type + ' */'
    if raw_type.startswith('ARRAY'):
        # append the details of the array as a comment
        details = ' '.join(raw_type.split(' ')[1:]);
        return 'ARRAY /* ' + details + ' */'
    return raw_type
        
def object_to_cpp(object, h_file):
    global namespace
    global indent
    section_name, sub_name = object_name_to_cpp_symbol(object['Name'])
    index = object_index_to_cpp_hex(object['Index'])
    subindex = object_subindex_to_cpp_number(object['SubIdx'])
    if ('SubIndex0' == sub_name) or ('' == object['SubIdx']) :
        if '' != namespace:
            print(f'}} // {namespace}', file=h_file)
            if '' == object['SubIdx'] :
                namespace = '' # back in the outer (CANopen) namespace
                indent = ''
            else:
                # entering a new namespace (section)
                namespace = section_name
                indent = '   '
                print(f'namespace {namespace} {{', file=h_file)
        else:
            # currently in outer namespace and possibly entering one
            if '' != object['SubIdx']:
                # entering a new namespace (section)
                namespace = section_name
                indent = '   '
                print(f'namespace {namespace} {{', file=h_file)
    if 'SubIndex0' != sub_name:
        comment = ''
        if 'Comment' in object:
            comment = ' // ' + object['Comment']
        type = translateType(object['Type'])
        print(f'{indent}const ObjectAddress {sub_name} = {{ {index}, {subindex}, Type::{type} }};{comment}', file=h_file)

import argparse
from esi_file import ObjectDictionary

parser = argparse.ArgumentParser(description='Extract object directory from EtherCAT ESI file as declarations in a C++ header')
parser.add_argument('input_filename', help='path of ESI file')
parser.add_argument('output_filename', help='path of H file')
args = parser.parse_args()

obj_dict = ObjectDictionary.from_file(args.input_filename)

with open(args.output_filename, 'wt', encoding='UTF-8') as h_file:
    h_file.write(boilerplate)
    for object in obj_dict.objects_dict.values():
        object_to_cpp(object, h_file)
    h_file.write(footer)
