# dump the object directory from an EtherCAT ESI file to a C++ header file

__version__ = '0.4.0'

import re

header1 = '''#pragma once

// generated by EsiObjDirToCPPHeader
'''

header2 = '''
#include <cstdint>
#include <array>

namespace CANopen {

enum class Type
{
   UNKNOWN,
   STRING, // length in comment
   ARRAY, // range and type in comment
   STRUCT, // size in bits comment
   BOOL,
   SINT,
   INT,
   DINT,
   LINT,
   USINT,
   BYTE,
   UINT,
   WORD,
   UDINT,
   DWORD,
   ULINT,
   LWORD,
   REAL,
   LREAL
};

'''

header3 = '''
struct ObjectAddress
{
   std::uint16_t index;
   std::uint8_t subindex;
   Type type;
   unsigned byteCount;
   const char* indexName;
   const char* subindexName;
   const char* description;
   constexpr ObjectAddress(std::uint16_t index_ = 0,
                           std::uint8_t subindex_ = 0,
                           Type type_ = Type::UNKNOWN,
                           unsigned byteCount_ = 0,
                           const char* indexName_ = "",
                           const char* subindexName_ = "",
                           const char* description_ = "") :
       index(index_),
       subindex(subindex_),
       type(type_),
       byteCount(byteCount_),
       indexName(indexName_),
       subindexName(subindexName_),
       description(description_)
   {}
   // "spaceship operator" returns -1, 0, 1
   // for sorting addresses by index::subindex
   // only index and subindex are relevant to comparison
   int compare(const ObjectAddress& other) const
   {
      if (index < other.index) return -1;
      if (index > other.index) return 1;
      if (subindex < other.subindex) return -1;
      if (subindex > other.subindex) return 1;
      return 0;
   }
};

inline bool operator<  (const ObjectAddress& o1, const ObjectAddress& o2) { return o1.compare(o2) <  0; }
inline bool operator<= (const ObjectAddress& o1, const ObjectAddress& o2) { return o1.compare(o2) <= 0; }
inline bool operator== (const ObjectAddress& o1, const ObjectAddress& o2) { return o1.compare(o2) == 0; }
inline bool operator>  (const ObjectAddress& o1, const ObjectAddress& o2) { return o1.compare(o2) >  0; }
inline bool operator>= (const ObjectAddress& o1, const ObjectAddress& o2) { return o1.compare(o2) >= 0; }
inline bool operator!= (const ObjectAddress& o1, const ObjectAddress& o2) { return o1.compare(o2) != 0; }

'''

footer = '''
} // namespace CANopen
'''

indent = ''
namespace = ''

def is_invalid_c_symbol(name):
    if not name:
        return True
    first_char = name[0]
    return not first_char.isalpha() and first_char != '_'

def object_name_to_cpp_symbol(name):
    if '/' in name:
        section, subsection = name.split('/')
    else:
        section = ''
        subsection = name
    # fixup names like 1st and 2nd by prefixing with X_
    if is_invalid_c_symbol(section):
        section = 'X_' + section
    if is_invalid_c_symbol(subsection):
        subsection = 'X_' + subsection
    return section.replace(' ', '_'), subsection.replace(' ', '_')

def object_index_to_cpp_hex(index):
    return index.replace('#', '0')

def object_subindex_to_cpp_number(subindex):
    if '' == subindex:
        return 0
    else:
        return int(subindex)

def translateType(raw_type):
    # if type is a string or enum, provide a proxy
    if '(' in raw_type:
        # for strings, remove the size, will be added as byteCount member
        return 'Type::' + re.sub(r'\(([0-9]+)\)', '', raw_type)
    # create aliases (below, in write_enum and write_subitemtype) so we can use original enum name here
    if raw_type.startswith('DT'):
        return raw_type
    if raw_type.startswith('ARRAY'):
        # append the details of the array as a comment
        details = ' '.join(raw_type.split(' ')[1:]);
        return 'Type::ARRAY /* ' + details + ' */'
    return 'Type::' + raw_type

def enter_namespace(section_name, index, h_file):
    namespace = section_name
    indent = '   '
    print(f'namespace {namespace} {{', file=h_file)
    print(f'{indent}constexpr std::uint16_t Index = {index};', file=h_file)
    return namespace, indent

def escape_quotes(s):
    return s.replace('"', '\\"')

def object_to_cpp(object, h_file):
    global namespace
    global indent
    section_name, sub_name = object_name_to_cpp_symbol(object['Name'])
    index = object_index_to_cpp_hex(object['Index'])
    subindex = object_subindex_to_cpp_number(object['SubIdx'])
    if ('SubIndex0' == sub_name) or ('' == object['SubIdx']) :
        if '' != namespace:
            print(f'}} // {namespace}', file=h_file)
            if '' == object['SubIdx'] :
                namespace = '' # back in the outer (CANopen) namespace
                indent = ''
            else:
                # entering a new namespace (section)
                namespace, indent = enter_namespace(section_name, index, h_file)
        else:
            # currently in outer namespace and possibly entering one
            if '' != object['SubIdx']:
                # entering a new namespace (section)
                namespace, indent = enter_namespace(section_name, index, h_file)
    if 'SubIndex0' != sub_name:
        comment = ''
        if 'Comment' in object:
            comment = escape_quotes(object['Comment'])
        type = translateType(object['Type'])
        byteCount = (int(object['BitSize']) + 7) // 8
        print(f'{indent}constexpr ObjectAddress {sub_name} {{ {index}, {subindex}, {type}, {byteCount}, "{namespace}", "{sub_name}", "{comment}" }};', file=h_file)
    return namespace, sub_name

def object_cpp_name(namespace, sub_name):
    if '' == namespace:
        return sub_name
    else:
        return f'{namespace}::{sub_name}';
    
def write_enum(name, enum, h_file):
    # typedef the name to its base type
    basetype = enum['BaseType']
    print(f'constexpr Type {name} = Type::{basetype};', file=h_file)

def write_subitemtype(name, subitemtype, h_file):
    # typedef the name to STRUCT or ARRAY
    if 'ArrayInfo' in subitemtype:
        type = 'ARRAY'
    else:
        type = 'STRUCT'
    print(f'constexpr Type {name} = Type::{type};', file=h_file)

import argparse
from esi_file import ObjectDictionary

parser = argparse.ArgumentParser(description='Extract object directory from EtherCAT ESI file as declarations in a C++ header')
parser.add_argument(
    '-v', '--version', 
    action='version', 
    version='%(prog)s ' + __version__
)
parser.add_argument('input_filename', help='path of ESI file')
parser.add_argument('output_filename', help='path of H file')
args = parser.parse_args()

obj_dict = ObjectDictionary.from_file(args.input_filename)

with open(args.output_filename, 'wt', encoding='UTF-8') as h_file:
    h_file.write(header1)
    # identify source and device(s)
    print(f'// from file {obj_dict.filename}', file=h_file)
    print(f'// for vendor {obj_dict.vendor}', file=h_file)
    print(f'// for device(s) {obj_dict.devices}', file=h_file)
    h_file.write(header2)
    for name, enum in obj_dict.enumtypes_dict.items():
        write_enum(name, enum, h_file)
    for name, subitemtype in obj_dict.subitemtypes_dict.items():
        write_subitemtype(name, subitemtype, h_file)
    h_file.write(header3)
    object_names = []
    object_count = 0
    for object in obj_dict.objects_dict.values():
        namespace, sub_name = object_to_cpp(object, h_file)
        if 'SubIndex0' != sub_name:
            object_names.append(object_cpp_name(namespace, sub_name))
            object_count = object_count + 1
    h_file.write(f'\nconstexpr std::array<ObjectAddress, {object_count}> objectAddresses{{\n   ');
    h_file.write(',\n   '.join(object_names))
    h_file.write('\n};\n');
    h_file.write(footer)
