# From ESI file, generate structured text code with a list of valid
# SDO object addresses.

__version__ = '0.1.0'

import argparse
from esi_file import ObjectDictionary

def object_index_to_st_hex(index):
    return index.replace('#x', '16#')

def object_subindex_to_st_decimal(subindex):
    if '' == subindex:
        return '0'
    else:
        return subindex

def object_to_sdo_decl(object, f, comma):
    name = object['Name']
    index = object_index_to_st_hex(object['Index'])
    subindex = object_subindex_to_st_decimal(object['SubIdx'])
    f.write(f'\t\t(wIndex := {index}, bySubIndex := {subindex}){comma}\t// {name}\n')
            
def main():

    parser = argparse.ArgumentParser(description='From ESI file, generate structured text code with a list of valid SDO object addresses')
    parser.add_argument(
        '-v', '--version', 
        action='version', 
        version='%(prog)s ' + __version__
    )
    parser.add_argument('input_filename', help='path of ESI file')
    # suggested output file extension is .gvl.st
    parser.add_argument('output_filename', help='path of ST GVL file')
    args = parser.parse_args()

    obj_dict = ObjectDictionary.from_file(args.input_filename)

    # Generate CODESYS Structured Text Configuration Fragment
    with open(args.output_filename, 'w', encoding='utf-8') as f:
        f.write('// Automatically generated by EsiToValidSdoList.py\n')
        f.write(f'// from {obj_dict.filename}\n')
        f.write(f'// for vendor {obj_dict.vendor}\n')
        f.write(f'// for device(s) {obj_dict.devices}\n')
        f.write('VAR_GLOBAL CONSTANT\n')
        f.write(f'\tMAX_VALID_SDOS : INT := {len(obj_dict.objects_dict)};\n')
        f.write('\taValidSDOs : ARRAY[1..MAX_VALID_SDOS] OF STRUCT_SDO_TARGET := [\n')
        last_key = next(reversed(obj_dict.objects_dict))
        for key, value in obj_dict.objects_dict.items():
            comma = '' if key == last_key else ','
            object_to_sdo_decl(value, f, comma)
        f.write('\t];\n')
        f.write('END_VAR\n')

if __name__ == '__main__':
    main()
